# Generated by Django 3.0.6 on 2020-06-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
